[package]
name = "Aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
historian_hysteria = { path = "../lib/historian_hysteria" }
red_nosed_reports = { path = "../lib/red_nosed_reports" }
mull_it_over = { path = "../lib/mull_it_over" }
ceres_search = { path = "../lib/ceres_search" }
print_queue = { path = "../lib/print_queue" }